/* The following code was generated by JFlex 1.6.1 */

import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>src/Lexer.lex</tt>
 */
class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;
  private static final String ZZ_NL = System.getProperty("line.separator");

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int CHARLITERAL = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\65\1\66\1\1\22\0\1\3\1\52\1\12"+
    "\1\4\2\0\1\51\1\13\1\54\1\55\1\43\1\41\1\56\1\42"+
    "\1\57\1\5\1\11\11\7\1\53\1\60\1\44\1\45\1\46\2\0"+
    "\32\6\1\61\1\14\1\62\1\47\1\10\1\0\1\16\1\31\1\22"+
    "\1\21\1\25\1\34\1\6\1\27\1\17\2\6\1\33\1\15\1\20"+
    "\1\32\1\35\1\26\1\30\1\24\1\23\1\40\1\36\1\37\3\6"+
    "\1\63\1\50\1\64\7\0\1\65\u1fa2\0\1\65\1\65\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\2\2\1\3\1\4\1\5\2\6\1\7"+
    "\1\10\20\5\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\2\1\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\2\34\1\35"+
    "\2\1\2\36\1\1\2\3\1\0\2\5\1\37\1\40"+
    "\1\5\1\41\11\5\1\42\1\5\1\43\6\5\1\44"+
    "\1\45\1\46\1\47\1\50\1\51\1\52\1\53\1\54"+
    "\1\55\1\56\1\57\1\60\1\61\1\62\1\63\10\36"+
    "\2\0\2\5\1\64\4\5\1\65\1\66\2\5\1\67"+
    "\3\5\1\70\6\5\1\71\1\72\1\73\1\74\1\75"+
    "\1\76\1\77\1\100\1\0\1\101\1\5\1\102\1\103"+
    "\1\104\1\105\1\106\1\107\1\110\1\5\1\111\1\112"+
    "\3\5\1\113\1\5\1\114\2\5\1\115\1\116\1\117"+
    "\1\120\1\121";

  private static int [] zzUnpackAction() {
    int [] result = new int[167];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\67\0\156\0\245\0\334\0\245\0\u0113\0\u014a"+
    "\0\u0181\0\u01b8\0\245\0\245\0\245\0\u01ef\0\u0226\0\u025d"+
    "\0\u0294\0\u02cb\0\u0302\0\u0339\0\u0370\0\u03a7\0\u03de\0\u0415"+
    "\0\u044c\0\u0483\0\u04ba\0\u04f1\0\u0528\0\245\0\245\0\245"+
    "\0\u055f\0\u0596\0\u05cd\0\245\0\u0604\0\u063b\0\u0672\0\u06a9"+
    "\0\245\0\245\0\245\0\245\0\245\0\245\0\245\0\245"+
    "\0\245\0\u06e0\0\u0717\0\245\0\245\0\u074e\0\u0785\0\u07bc"+
    "\0\245\0\u07f3\0\u082a\0\245\0\u0861\0\u0898\0\u08cf\0\u0906"+
    "\0\u0181\0\u093d\0\u0181\0\u0974\0\u09ab\0\u09e2\0\u0a19\0\u0a50"+
    "\0\u0a87\0\u0abe\0\u0af5\0\u0b2c\0\u0181\0\u0b63\0\u0181\0\u0b9a"+
    "\0\u0bd1\0\u0c08\0\u0c3f\0\u0c76\0\u0cad\0\245\0\245\0\245"+
    "\0\245\0\245\0\245\0\245\0\245\0\245\0\245\0\245"+
    "\0\245\0\245\0\245\0\245\0\245\0\u0ce4\0\u0d1b\0\u0d52"+
    "\0\u0d89\0\u0dc0\0\u0df7\0\u0e2e\0\u0e65\0\u0e9c\0\u0ed3\0\u0f0a"+
    "\0\u0f41\0\u0181\0\u0f78\0\u0faf\0\u0fe6\0\u101d\0\u0181\0\u0181"+
    "\0\u1054\0\u108b\0\u0181\0\u10c2\0\u10f9\0\u1130\0\u0181\0\u1167"+
    "\0\u119e\0\u11d5\0\u120c\0\u1243\0\u127a\0\245\0\245\0\245"+
    "\0\245\0\245\0\245\0\245\0\245\0\u12b1\0\u0181\0\u12e8"+
    "\0\u0181\0\u0181\0\u0181\0\u0181\0\u0181\0\u0181\0\u0181\0\u131f"+
    "\0\u0181\0\u0181\0\u1356\0\u138d\0\u13c4\0\u0181\0\u13fb\0\u0181"+
    "\0\u1432\0\u1469\0\u0181\0\u0181\0\u0181\0\u0181\0\u0181";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[167];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\2\6\1\7\1\10\1\11\1\12\1\4"+
    "\1\13\1\14\1\15\1\4\1\16\1\17\1\20\1\11"+
    "\1\21\1\22\1\23\1\24\1\25\2\11\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\11\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\1\50\1\51\1\52\1\53\1\54\1\55\1\56"+
    "\1\57\1\60\1\61\1\4\1\6\1\62\1\63\1\64"+
    "\7\62\1\65\1\62\1\66\52\62\1\67\1\70\1\71"+
    "\10\67\1\4\1\72\52\67\71\0\1\6\64\0\1\7"+
    "\1\73\1\74\64\7\4\0\1\75\70\0\4\11\3\0"+
    "\24\11\35\0\1\12\1\0\1\12\63\0\4\11\3\0"+
    "\1\11\1\76\22\11\34\0\4\11\3\0\16\11\1\77"+
    "\5\11\34\0\4\11\3\0\3\11\1\100\13\11\1\101"+
    "\4\11\34\0\4\11\3\0\2\11\1\102\12\11\1\103"+
    "\6\11\34\0\4\11\3\0\12\11\1\104\11\11\34\0"+
    "\4\11\3\0\4\11\1\105\5\11\1\106\2\11\1\107"+
    "\6\11\34\0\4\11\3\0\10\11\1\110\13\11\34\0"+
    "\4\11\3\0\16\11\1\111\5\11\34\0\4\11\3\0"+
    "\1\11\1\112\6\11\1\113\13\11\34\0\4\11\3\0"+
    "\15\11\1\114\6\11\34\0\4\11\3\0\4\11\1\115"+
    "\17\11\34\0\4\11\3\0\10\11\1\116\13\11\34\0"+
    "\4\11\3\0\2\11\1\117\1\11\1\120\10\11\1\121"+
    "\1\122\5\11\34\0\4\11\3\0\13\11\1\123\10\11"+
    "\34\0\4\11\3\0\15\11\1\124\6\11\34\0\4\11"+
    "\3\0\12\11\1\125\11\11\73\0\1\126\66\0\1\127"+
    "\66\0\1\130\71\0\1\131\67\0\1\132\62\0\1\133"+
    "\74\0\1\134\13\0\1\62\2\0\7\62\1\0\1\62"+
    "\1\0\52\62\2\0\1\64\64\0\1\64\2\0\7\64"+
    "\1\135\1\136\1\137\3\64\1\140\2\64\1\141\4\64"+
    "\1\142\1\143\2\64\1\144\30\64\15\0\1\145\55\0"+
    "\1\71\64\0\1\71\2\0\7\71\1\146\1\147\1\150"+
    "\3\71\1\151\2\71\1\152\4\71\1\153\1\154\2\71"+
    "\1\155\30\71\4\0\1\74\64\0\4\156\1\157\62\156"+
    "\6\0\4\11\3\0\2\11\1\160\21\11\34\0\4\11"+
    "\3\0\2\11\1\161\21\11\34\0\4\11\3\0\6\11"+
    "\1\162\15\11\34\0\4\11\3\0\5\11\1\163\16\11"+
    "\34\0\4\11\3\0\1\11\1\164\22\11\34\0\4\11"+
    "\3\0\10\11\1\165\13\11\34\0\4\11\3\0\10\11"+
    "\1\166\13\11\34\0\4\11\3\0\20\11\1\167\3\11"+
    "\34\0\4\11\3\0\11\11\1\170\12\11\34\0\4\11"+
    "\3\0\2\11\1\171\4\11\1\172\14\11\34\0\4\11"+
    "\3\0\6\11\1\173\15\11\34\0\4\11\3\0\1\11"+
    "\1\174\4\11\1\175\15\11\34\0\4\11\3\0\15\11"+
    "\1\176\6\11\34\0\4\11\3\0\3\11\1\177\20\11"+
    "\34\0\4\11\3\0\10\11\1\200\13\11\34\0\4\11"+
    "\3\0\13\11\1\201\10\11\34\0\4\11\3\0\15\11"+
    "\1\202\6\11\34\0\4\11\3\0\2\11\1\203\21\11"+
    "\34\0\4\11\3\0\2\11\1\204\21\11\34\0\4\11"+
    "\3\0\2\11\1\205\21\11\41\0\1\206\66\0\1\207"+
    "\66\0\1\210\66\0\1\211\66\0\1\212\66\0\1\213"+
    "\66\0\1\214\66\0\1\215\53\0\4\156\1\216\62\156"+
    "\4\0\1\157\1\74\67\0\4\11\3\0\3\11\1\217"+
    "\20\11\34\0\4\11\3\0\1\11\1\220\22\11\34\0"+
    "\4\11\3\0\6\11\1\221\15\11\34\0\4\11\3\0"+
    "\13\11\1\222\10\11\34\0\4\11\3\0\17\11\1\223"+
    "\4\11\34\0\4\11\3\0\3\11\1\224\20\11\34\0"+
    "\4\11\3\0\17\11\1\225\4\11\34\0\4\11\3\0"+
    "\10\11\1\226\13\11\34\0\4\11\3\0\4\11\1\227"+
    "\17\11\34\0\4\11\3\0\23\11\1\230\34\0\4\11"+
    "\3\0\16\11\1\231\5\11\34\0\4\11\3\0\17\11"+
    "\1\232\4\11\34\0\4\11\3\0\1\11\1\233\22\11"+
    "\34\0\4\11\3\0\1\11\1\234\22\11\34\0\4\11"+
    "\3\0\3\11\1\235\20\11\34\0\4\11\3\0\4\11"+
    "\1\236\17\11\34\0\4\11\3\0\16\11\1\237\5\11"+
    "\26\0\4\156\1\216\1\74\61\156\6\0\4\11\3\0"+
    "\7\11\1\240\14\11\34\0\4\11\3\0\13\11\1\241"+
    "\10\11\34\0\4\11\3\0\16\11\1\242\5\11\34\0"+
    "\4\11\3\0\6\11\1\243\15\11\34\0\4\11\3\0"+
    "\6\11\1\244\15\11\34\0\4\11\3\0\10\11\1\245"+
    "\13\11\34\0\4\11\3\0\3\11\1\246\20\11\34\0"+
    "\4\11\3\0\16\11\1\247\5\11\26\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5280];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\1\1\1\11\4\1\3\11\20\1\3\11"+
    "\3\1\1\11\4\1\11\11\2\1\2\11\3\1\1\11"+
    "\2\1\1\11\1\0\30\1\20\11\10\1\2\0\26\1"+
    "\10\11\1\0\31\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[167];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
	StringBuffer string = new StringBuffer();
	private Symbol symbol(int type) {
		return new Symbol(type, yyline, yycolumn);
	}
	private Symbol symbol(int type, Object value) {
		return new Symbol(type, yyline, yycolumn, value);
	}


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 170) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  private static String zzToPrintable(String str) {
    StringBuilder builder = new StringBuilder();
    for (int n = 0 ; n < str.length() ; ) {
      int ch = str.codePointAt(n);
      int charCount = Character.charCount(ch);
      n += charCount;
      if (ch > 31 && ch < 127) {
        builder.append((char)ch);
      } else if (charCount == 1) {
        builder.append(String.format("\\u%04X", ch));
      } else {
        builder.append(String.format("\\U%06X", ch));
      }
    }
    return builder.toString();
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { 	return symbol(sym.EOF);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [189] { throw new Error(\"Illegal Character <\" + yytext() + \">\"); }");
            { throw new Error("Illegal Character <" + yytext() + ">");
            }
          case 82: break;
          case 2: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [145] { /*\tDon\'t do anything */ }");
            { /*	Don't do anything */
            }
          case 83: break;
          case 3: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [146] { /* Don\'t do anything */ }");
            { /* Don't do anything */
            }
          case 84: break;
          case 4: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [94] { return symbol(sym.SYM_DIV); }");
            { return symbol(sym.SYM_DIV);
            }
          case 85: break;
          case 5: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [143] { return symbol(sym.IDENT,yytext()); }");
            { return symbol(sym.IDENT,yytext());
            }
          case 86: break;
          case 6: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [144] { return symbol(sym.INT_LITERAL,new Integer(yytext())); }");
            { return symbol(sym.INT_LITERAL,new Integer(yytext()));
            }
          case 87: break;
          case 7: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [55] { string.setLength(0); yybegin(STRING); }");
            { string.setLength(0); yybegin(STRING);
            }
          case 88: break;
          case 8: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [56] { yybegin(CHARLITERAL); }");
            { yybegin(CHARLITERAL);
            }
          case 89: break;
          case 9: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [91] { return symbol(sym.SYM_PLUS); }");
            { return symbol(sym.SYM_PLUS);
            }
          case 90: break;
          case 10: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [92] { return symbol(sym.SYM_MINUS); }");
            { return symbol(sym.SYM_MINUS);
            }
          case 91: break;
          case 11: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [93] { return symbol(sym.SYM_STAR); }");
            { return symbol(sym.SYM_STAR);
            }
          case 92: break;
          case 12: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [95] { return symbol(sym.SYM_LARROW); }");
            { return symbol(sym.SYM_LARROW);
            }
          case 93: break;
          case 13: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [96] { return symbol(sym.SYM_EQUAL); }");
            { return symbol(sym.SYM_EQUAL);
            }
          case 94: break;
          case 14: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [97] { return symbol(sym.SYM_RARROW); }");
            { return symbol(sym.SYM_RARROW);
            }
          case 95: break;
          case 15: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [98] { return symbol(sym.SYM_CARET); }");
            { return symbol(sym.SYM_CARET);
            }
          case 96: break;
          case 16: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [110] { return symbol(sym.SYM_EXCLPNT); }");
            { return symbol(sym.SYM_EXCLPNT);
            }
          case 97: break;
          case 17: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [121] { return symbol(sym.SYM_COLON); }");
            { return symbol(sym.SYM_COLON);
            }
          case 98: break;
          case 18: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [117] { return symbol(sym.SYM_LPAREN); }");
            { return symbol(sym.SYM_LPAREN);
            }
          case 99: break;
          case 19: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [118] { return symbol(sym.SYM_RPAREN); }");
            { return symbol(sym.SYM_RPAREN);
            }
          case 100: break;
          case 20: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [119] { return symbol(sym.SYM_COMMA); }");
            { return symbol(sym.SYM_COMMA);
            }
          case 101: break;
          case 21: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [120] { return symbol(sym.SYM_PERIOD); }");
            { return symbol(sym.SYM_PERIOD);
            }
          case 102: break;
          case 22: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [122] { return symbol(sym.SYM_SEMI); }");
            { return symbol(sym.SYM_SEMI);
            }
          case 103: break;
          case 23: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [125] { return symbol(sym.SYM_LSQR); }");
            { return symbol(sym.SYM_LSQR);
            }
          case 104: break;
          case 24: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [126] { return symbol(sym.SYM_RSQR); }");
            { return symbol(sym.SYM_RSQR);
            }
          case 105: break;
          case 25: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [127] { return symbol(sym.SYM_LCRL); }");
            { return symbol(sym.SYM_LCRL);
            }
          case 106: break;
          case 26: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [128] { return symbol(sym.SYM_RCRL); }");
            { return symbol(sym.SYM_RCRL);
            }
          case 107: break;
          case 27: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [154] { string.append(yytext()); }");
            { string.append(yytext());
            }
          case 108: break;
          case 28: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [166] { throw new Error(\"Illegal Termination of String <\" + yytext() + \">\"); }");
            { throw new Error("Illegal Termination of String <" + yytext() + ">");
            }
          case 109: break;
          case 29: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [151] { yybegin(YYINITIAL);"+ZZ_NL+"\t\t\t\t\t\t\treturn symbol(sym.STRING_LITERAL,"+ZZ_NL+"\t\t\t\t\t\t\tstring.toString()); }");
            { yybegin(YYINITIAL);
							return symbol(sym.STRING_LITERAL,
							string.toString());
            }
          case 110: break;
          case 30: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [184] { throw new Error(\"Illegal Termination of Character <\" + yytext() + \">\"); }");
            { throw new Error("Illegal Termination of Character <" + yytext() + ">");
            }
          case 111: break;
          case 31: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [69] { return symbol(sym.IN); }");
            { return symbol(sym.IN);
            }
          case 112: break;
          case 32: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [75] { return symbol(sym.IFEL); }");
            { return symbol(sym.IFEL);
            }
          case 113: break;
          case 33: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [84] { return symbol(sym.DO); }");
            { return symbol(sym.DO);
            }
          case 114: break;
          case 34: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [85] { return symbol(sym.OD); }");
            { return symbol(sym.OD);
            }
          case 115: break;
          case 35: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [83] { return symbol(sym.FI); }");
            { return symbol(sym.FI);
            }
          case 116: break;
          case 36: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [100] { return symbol(sym.LEQ); }");
            { return symbol(sym.LEQ);
            }
          case 117: break;
          case 37: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [107] { return symbol(sym.EQEQ); }");
            { return symbol(sym.EQEQ);
            }
          case 118: break;
          case 38: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [101] { return symbol(sym.GEQ); }");
            { return symbol(sym.GEQ);
            }
          case 119: break;
          case 39: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [105] { return symbol(sym.SYM_OR); }");
            { return symbol(sym.SYM_OR);
            }
          case 120: break;
          case 40: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [106] { return symbol(sym.SYM_AND); }");
            { return symbol(sym.SYM_AND);
            }
          case 121: break;
          case 41: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [108] { return symbol(sym.NOTEQ); }");
            { return symbol(sym.NOTEQ);
            }
          case 122: break;
          case 42: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [109] { return symbol(sym.CONCAT); }");
            { return symbol(sym.CONCAT);
            }
          case 123: break;
          case 43: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [160] { string.append(\'\\\"\'); }");
            { string.append('\"');
            }
          case 124: break;
          case 44: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [161] { string.append(\'\\\'\'); }");
            { string.append('\'');
            }
          case 125: break;
          case 45: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [162] { string.append(\'\\\\\'); }");
            { string.append('\\');
            }
          case 126: break;
          case 46: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [158] { string.append(\'\\n\'); }");
            { string.append('\n');
            }
          case 127: break;
          case 47: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [157] { string.append(\'\\t\'); }");
            { string.append('\t');
            }
          case 128: break;
          case 48: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [159] { string.append(\'\\r\'); }");
            { string.append('\r');
            }
          case 129: break;
          case 49: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [155] { string.append(\'\\b\'); }");
            { string.append('\b');
            }
          case 130: break;
          case 50: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [156] { string.append(\'\\f\'); }");
            { string.append('\f');
            }
          case 131: break;
          case 51: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [172] { yybegin(YYINITIAL);return symbol(sym.CHAR_LITERAL,yytext().charAt(0)); }");
            { yybegin(YYINITIAL);return symbol(sym.CHAR_LITERAL,yytext().charAt(0));
            }
          case 132: break;
          case 52: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [65] { return symbol(sym.INT); }");
            { return symbol(sym.INT);
            }
          case 133: break;
          case 53: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [68] { return symbol(sym.TOP); }");
            { return symbol(sym.TOP);
            }
          case 134: break;
          case 54: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [62] { return symbol(sym.SEQ); }");
            { return symbol(sym.SEQ);
            }
          case 135: break;
          case 55: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [66] { return symbol(sym.RAT); }");
            { return symbol(sym.RAT);
            }
          case 136: break;
          case 56: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [70] { return symbol(sym.LEN); }");
            { return symbol(sym.LEN);
            }
          case 137: break;
          case 57: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [178] { yybegin(YYINITIAL); return symbol(sym.CHAR_LITERAL, \'\\\"\'); }");
            { yybegin(YYINITIAL); return symbol(sym.CHAR_LITERAL, '\"');
            }
          case 138: break;
          case 58: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [179] { yybegin(YYINITIAL); return symbol(sym.CHAR_LITERAL, \'\\\'\'); }");
            { yybegin(YYINITIAL); return symbol(sym.CHAR_LITERAL, '\'');
            }
          case 139: break;
          case 59: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [180] { yybegin(YYINITIAL); return symbol(sym.CHAR_LITERAL, \'\\\\\'); }");
            { yybegin(YYINITIAL); return symbol(sym.CHAR_LITERAL, '\\');
            }
          case 140: break;
          case 60: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [176] { yybegin(YYINITIAL); return symbol(sym.CHAR_LITERAL, \'\\n\'); }");
            { yybegin(YYINITIAL); return symbol(sym.CHAR_LITERAL, '\n');
            }
          case 141: break;
          case 61: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [175] { yybegin(YYINITIAL); return symbol(sym.CHAR_LITERAL, \'\\t\'); }");
            { yybegin(YYINITIAL); return symbol(sym.CHAR_LITERAL, '\t');
            }
          case 142: break;
          case 62: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [177] { yybegin(YYINITIAL); return symbol(sym.CHAR_LITERAL, \'\\r\'); }");
            { yybegin(YYINITIAL); return symbol(sym.CHAR_LITERAL, '\r');
            }
          case 143: break;
          case 63: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [173] { yybegin(YYINITIAL); return symbol(sym.CHAR_LITERAL, \'\\b\'); }");
            { yybegin(YYINITIAL); return symbol(sym.CHAR_LITERAL, '\b');
            }
          case 144: break;
          case 64: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [174] { yybegin(YYINITIAL); return symbol(sym.CHAR_LITERAL, \'\\f\'); }");
            { yybegin(YYINITIAL); return symbol(sym.CHAR_LITERAL, '\f');
            }
          case 145: break;
          case 65: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [60] { return symbol(sym.MAIN); }");
            { return symbol(sym.MAIN);
            }
          case 146: break;
          case 66: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [61] { return symbol(sym.DICT); }");
            { return symbol(sym.DICT);
            }
          case 147: break;
          case 67: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [63] { return symbol(sym.CHAR); }");
            { return symbol(sym.CHAR);
            }
          case 148: break;
          case 68: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [71] { return symbol(sym.TDEF); }");
            { return symbol(sym.TDEF);
            }
          case 149: break;
          case 69: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [82] { return symbol(sym.THEN); }");
            { return symbol(sym.THEN);
            }
          case 150: break;
          case 70: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [77] { return symbol(sym.ELIF); }");
            { return symbol(sym.ELIF);
            }
          case 151: break;
          case 71: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [76] { return symbol(sym.ELSE); }");
            { return symbol(sym.ELSE);
            }
          case 152: break;
          case 72: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [80] { return symbol(sym.READ); }");
            { return symbol(sym.READ);
            }
          case 153: break;
          case 73: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [64] { return symbol(sym.BOOL); }");
            { return symbol(sym.BOOL);
            }
          case 154: break;
          case 74: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [72] { return symbol(sym.FDEF); }");
            { return symbol(sym.FDEF);
            }
          case 155: break;
          case 75: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [74] { return symbol(sym.VOID); }");
            { return symbol(sym.VOID);
            }
          case 156: break;
          case 76: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [73] { return symbol(sym.ALIAS); }");
            { return symbol(sym.ALIAS);
            }
          case 157: break;
          case 77: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [67] { return symbol(sym.FLOAT); }");
            { return symbol(sym.FLOAT);
            }
          case 158: break;
          case 78: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [81] { return symbol(sym.PRINT); }");
            { return symbol(sym.PRINT);
            }
          case 159: break;
          case 79: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [78] { return symbol(sym.WHILE); }");
            { return symbol(sym.WHILE);
            }
          case 160: break;
          case 80: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [86] { return symbol(sym.RETURN); }");
            { return symbol(sym.RETURN);
            }
          case 161: break;
          case 81: 
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [79] { return symbol(sym.FORALL); }");
            { return symbol(sym.FORALL);
            }
          case 162: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This main method is the debugging routine for the scanner.
   * It prints debugging information about each returned token to
   * System.out until the end of file is reached, or an error occured.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java Lexer [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          java.nio.charset.Charset.forName(encodingName); // Side-effect: is encodingName valid? 
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        Lexer scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new Lexer(reader);
          do {
            System.out.println(scanner.next_token());
          } while (!scanner.zzAtEOF);

        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
