
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LEN = 66;
  public static final int SYM_EQUAL = 8;
  public static final int BOOL = 45;
  public static final int SYM_SEMI = 29;
  public static final int READ = 71;
  public static final int INT_LITERAL = 59;
  public static final int SYM_AMP = 23;
  public static final int NOTEQ = 18;
  public static final int IFEL = 49;
  public static final int TOP = 64;
  public static final int SYM_LCRL = 34;
  public static final int FDEF = 68;
  public static final int GEQ = 14;
  public static final int DICT = 42;
  public static final int SYM_BLASH = 36;
  public static final int SYM_AT = 31;
  public static final int ELIF = 52;
  public static final int SYM_MINUS = 3;
  public static final int FI = 73;
  public static final int SYM_RCRL = 35;
  public static final int FLOAT = 48;
  public static final int SYM_BSLASH = 7;
  public static final int THEN = 50;
  public static final int SYM_COLON = 28;
  public static final int SYM_CARET = 11;
  public static final int SYM_PRCNT = 12;
  public static final int SYM_PIPE = 40;
  public static final int SYM_QSTN = 30;
  public static final int SYM_PLUS = 2;
  public static final int SYM_RARROW = 10;
  public static final int SYM_EXCLPNT = 20;
  public static final int RAT = 47;
  public static final int ALIAS = 69;
  public static final int FORALL = 54;
  public static final int SYM_LARROW = 9;
  public static final int WHILE = 53;
  public static final int SYM_STAR = 4;
  public static final int TDEF = 67;
  public static final int CHAR = 44;
  public static final int DO = 55;
  public static final int VOID = 70;
  public static final int RETURN = 56;
  public static final int CONCAT = 19;
  public static final int ELSE = 51;
  public static final int INT = 46;
  public static final int SYM_DIV = 5;
  public static final int STRING_LITERAL = 60;
  public static final int EQEQ = 17;
  public static final int EOF = 0;
  public static final int PRINT = 72;
  public static final int SYM_COMMA = 26;
  public static final int MAIN = 41;
  public static final int RAT_LITERAL = 63;
  public static final int FLOAT_LITERAL = 62;
  public static final int SYM_PERIOD = 27;
  public static final int IN = 65;
  public static final int SYM_LSQR = 32;
  public static final int IDENT = 57;
  public static final int error = 1;
  public static final int SEQ = 43;
  public static final int SYM_USCORE = 37;
  public static final int SYM_TILDE = 39;
  public static final int OD = 74;
  public static final int SYM_RPAREN = 25;
  public static final int CHAR_LITERAL = 58;
  public static final int SYM_LPAREN = 24;
  public static final int SYM_RSQR = 33;
  public static final int SYM_DOLLAR = 22;
  public static final int SYM_GRAVE = 38;
  public static final int SYM_OR = 15;
  public static final int SYM_HASH = 21;
  public static final int SYM_FSLASH = 6;
  public static final int BOOL_LITERAL = 61;
  public static final int LEQ = 13;
  public static final int SYM_AND = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SYM_PLUS",
  "SYM_MINUS",
  "SYM_STAR",
  "SYM_DIV",
  "SYM_FSLASH",
  "SYM_BSLASH",
  "SYM_EQUAL",
  "SYM_LARROW",
  "SYM_RARROW",
  "SYM_CARET",
  "SYM_PRCNT",
  "LEQ",
  "GEQ",
  "SYM_OR",
  "SYM_AND",
  "EQEQ",
  "NOTEQ",
  "CONCAT",
  "SYM_EXCLPNT",
  "SYM_HASH",
  "SYM_DOLLAR",
  "SYM_AMP",
  "SYM_LPAREN",
  "SYM_RPAREN",
  "SYM_COMMA",
  "SYM_PERIOD",
  "SYM_COLON",
  "SYM_SEMI",
  "SYM_QSTN",
  "SYM_AT",
  "SYM_LSQR",
  "SYM_RSQR",
  "SYM_LCRL",
  "SYM_RCRL",
  "SYM_BLASH",
  "SYM_USCORE",
  "SYM_GRAVE",
  "SYM_TILDE",
  "SYM_PIPE",
  "MAIN",
  "DICT",
  "SEQ",
  "CHAR",
  "BOOL",
  "INT",
  "RAT",
  "FLOAT",
  "IFEL",
  "THEN",
  "ELSE",
  "ELIF",
  "WHILE",
  "FORALL",
  "DO",
  "RETURN",
  "IDENT",
  "CHAR_LITERAL",
  "INT_LITERAL",
  "STRING_LITERAL",
  "BOOL_LITERAL",
  "FLOAT_LITERAL",
  "RAT_LITERAL",
  "TOP",
  "IN",
  "LEN",
  "TDEF",
  "FDEF",
  "ALIAS",
  "VOID",
  "READ",
  "PRINT",
  "FI",
  "OD"
  };
}

