
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FORALL = 42;
  public static final int SEQ = 31;
  public static final int STRING_LITERAL = 48;
  public static final int SYM_EQUAL = 6;
  public static final int CHAR = 32;
  public static final int CHAR_LITERAL = 46;
  public static final int CONCAT = 16;
  public static final int INT = 34;
  public static final int SYM_RSQR = 25;
  public static final int SYM_COLON = 22;
  public static final int SYM_LARROW = 7;
  public static final int SYM_LCRL = 26;
  public static final int TDEF = 53;
  public static final int IN = 51;
  public static final int BOOL = 33;
  public static final int SYM_AND = 13;
  public static final int FI = 59;
  public static final int RAT = 35;
  public static final int GEQ = 11;
  public static final int SYM_RARROW = 8;
  public static final int MAIN = 29;
  public static final int SYM_USCORE = 28;
  public static final int SYM_OR = 12;
  public static final int SYM_DIV = 5;
  public static final int EOF = 0;
  public static final int OD = 60;
  public static final int RETURN = 44;
  public static final int SYM_PERIOD = 21;
  public static final int error = 1;
  public static final int IFEL = 37;
  public static final int EQEQ = 14;
  public static final int SYM_LPAREN = 18;
  public static final int FDEF = 54;
  public static final int IDENT = 45;
  public static final int VOID = 56;
  public static final int TOP = 50;
  public static final int SYM_SEMI = 23;
  public static final int SYM_RPAREN = 19;
  public static final int ELSE = 39;
  public static final int DICT = 30;
  public static final int SYM_STAR = 4;
  public static final int READ = 57;
  public static final int SYM_LSQR = 24;
  public static final int WHILE = 41;
  public static final int FLOAT = 36;
  public static final int SYM_MINUS = 3;
  public static final int THEN = 38;
  public static final int SYM_RCRL = 27;
  public static final int SYM_EXCLPNT = 17;
  public static final int LEQ = 10;
  public static final int LEN = 52;
  public static final int ALIAS = 55;
  public static final int SYM_PLUS = 2;
  public static final int SYM_COMMA = 20;
  public static final int ELIF = 40;
  public static final int PRINT = 58;
  public static final int BOOL_LITERAL = 49;
  public static final int DO = 43;
  public static final int INT_LITERAL = 47;
  public static final int NOTEQ = 15;
  public static final int SYM_CARET = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SYM_PLUS",
  "SYM_MINUS",
  "SYM_STAR",
  "SYM_DIV",
  "SYM_EQUAL",
  "SYM_LARROW",
  "SYM_RARROW",
  "SYM_CARET",
  "LEQ",
  "GEQ",
  "SYM_OR",
  "SYM_AND",
  "EQEQ",
  "NOTEQ",
  "CONCAT",
  "SYM_EXCLPNT",
  "SYM_LPAREN",
  "SYM_RPAREN",
  "SYM_COMMA",
  "SYM_PERIOD",
  "SYM_COLON",
  "SYM_SEMI",
  "SYM_LSQR",
  "SYM_RSQR",
  "SYM_LCRL",
  "SYM_RCRL",
  "SYM_USCORE",
  "MAIN",
  "DICT",
  "SEQ",
  "CHAR",
  "BOOL",
  "INT",
  "RAT",
  "FLOAT",
  "IFEL",
  "THEN",
  "ELSE",
  "ELIF",
  "WHILE",
  "FORALL",
  "DO",
  "RETURN",
  "IDENT",
  "CHAR_LITERAL",
  "INT_LITERAL",
  "STRING_LITERAL",
  "BOOL_LITERAL",
  "TOP",
  "IN",
  "LEN",
  "TDEF",
  "FDEF",
  "ALIAS",
  "VOID",
  "READ",
  "PRINT",
  "FI",
  "OD"
  };
}

